// Code generated by go generate; DO NOT EDIT.

package inzure



type TLSVersion int

const (
	TLSVersionUnknown TLSVersion = 0
    TLSVersionOneZero TLSVersion = 1
    TLSVersionOneOne TLSVersion = 2
    TLSVersionOneTwo TLSVersion = 3
)

func (it TLSVersion) IsUnknown() bool {
	return it == TLSVersionUnknown
}

func (it TLSVersion) IsKnown() bool {
	return it != TLSVersionUnknown
}

func (it TLSVersion) IsOneZero() UnknownBool {
	if it == TLSVersionUnknown {
		return BoolUnknown
	}
	return UnknownFromBool(it == TLSVersionOneZero)
}

func (it TLSVersion) IsOneOne() UnknownBool {
	if it == TLSVersionUnknown {
		return BoolUnknown
	}
	return UnknownFromBool(it == TLSVersionOneOne)
}

func (it TLSVersion) IsOneTwo() UnknownBool {
	if it == TLSVersionUnknown {
		return BoolUnknown
	}
	return UnknownFromBool(it == TLSVersionOneTwo)
}


