// Code generated by go generate; DO NOT EDIT.

package inzure


import (
	"fmt"
	azpkg "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/apimanagement/armapimanagement"
)


type APIServiceVNetType int

const (
    APIServiceVNetTypeNone APIServiceVNetType = 0
    APIServiceVNetTypeExternal APIServiceVNetType = 1
    APIServiceVNetTypeInternal APIServiceVNetType = 2
)



func (it *APIServiceVNetType) FromAzure(az *azpkg.VirtualNetworkType) {
	if (az == nil) {
		*it = APIServiceVNetType(0)
		return
	}
	switch(*az) {
	case azpkg.VirtualNetworkTypeNone:
		*it = APIServiceVNetTypeNone
	case azpkg.VirtualNetworkTypeExternal:
		*it = APIServiceVNetTypeExternal
	case azpkg.VirtualNetworkTypeInternal:
		*it = APIServiceVNetTypeInternal
	default:
		*it = APIServiceVNetType(0)
	}
}

func (it APIServiceVNetType) IsNone() bool {
	return it == APIServiceVNetTypeNone
}


func (it APIServiceVNetType) IsExternal() bool {
	return it == APIServiceVNetTypeExternal
}


func (it APIServiceVNetType) IsInternal() bool {
	return it == APIServiceVNetTypeInternal
}


func (it APIServiceVNetType) String() string {
	switch (it) {
	case APIServiceVNetTypeNone:
		return "None"
	case APIServiceVNetTypeExternal:
		return "External"
	case APIServiceVNetTypeInternal:
		return "Internal"
	default:
		return fmt.Sprintf("APIServiceVNetType(%d)", it)
	}
}

