// Code generated by go generate; DO NOT EDIT.

package inzure


import (
	azpkg "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/dashboard/armdashboard"
)


type StartTLSPolicy int

const (
	StartTLSUnknown StartTLSPolicy = 0
    StartTLSMandatory StartTLSPolicy = 1
    StartTLSNone StartTLSPolicy = 2
    StartTLSOpportunistic StartTLSPolicy = 3
)



func (it *StartTLSPolicy) FromAzure(az *azpkg.StartTLSPolicy) {
	if (az == nil) {
		*it = StartTLSUnknown
		return
	}
	switch(*az) {
	case azpkg.StartTLSPolicyMandatoryStartTLS:
		*it = StartTLSMandatory
	case azpkg.StartTLSPolicyNoStartTLS:
		*it = StartTLSNone
	case azpkg.StartTLSPolicyOpportunisticStartTLS:
		*it = StartTLSOpportunistic
	default:
		*it = StartTLSUnknown
	}
}
func (it StartTLSPolicy) IsUnknown() bool {
	return it == StartTLSUnknown
}

func (it StartTLSPolicy) IsKnown() bool {
	return it != StartTLSUnknown
}

func (it StartTLSPolicy) IsMandatory() UnknownBool {
	if it == StartTLSUnknown {
		return BoolUnknown
	}
	return UnknownFromBool(it == StartTLSMandatory)
}

func (it StartTLSPolicy) IsNone() UnknownBool {
	if it == StartTLSUnknown {
		return BoolUnknown
	}
	return UnknownFromBool(it == StartTLSNone)
}

func (it StartTLSPolicy) IsOpportunistic() UnknownBool {
	if it == StartTLSUnknown {
		return BoolUnknown
	}
	return UnknownFromBool(it == StartTLSOpportunistic)
}


