// Code generated by go generate; DO NOT EDIT.

package inzure


import (
	azpkg "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/network/armnetwork/v8"
)


type ProvisioningState int

const (
	ProvisioningUnknown ProvisioningState = 0
    ProvisioningCanceled ProvisioningState = 1
    ProvisioningCreating ProvisioningState = 2
    ProvisioningDeleting ProvisioningState = 3
    ProvisioningFailed ProvisioningState = 4
    ProvisioningSucceeded ProvisioningState = 5
    ProvisioningUpdating ProvisioningState = 6
)



func (it *ProvisioningState) FromAzure(az *azpkg.ProvisioningState) {
	if (az == nil) {
		*it = ProvisioningUnknown
		return
	}
	switch(*az) {
	case azpkg.ProvisioningStateCanceled:
		*it = ProvisioningCanceled
	case azpkg.ProvisioningStateCreating:
		*it = ProvisioningCreating
	case azpkg.ProvisioningStateDeleting:
		*it = ProvisioningDeleting
	case azpkg.ProvisioningStateFailed:
		*it = ProvisioningFailed
	case azpkg.ProvisioningStateSucceeded:
		*it = ProvisioningSucceeded
	case azpkg.ProvisioningStateUpdating:
		*it = ProvisioningUpdating
	default:
		*it = ProvisioningUnknown
	}
}
func (it ProvisioningState) IsUnknown() bool {
	return it == ProvisioningUnknown
}

func (it ProvisioningState) IsKnown() bool {
	return it != ProvisioningUnknown
}

func (it ProvisioningState) IsCanceled() UnknownBool {
	if it == ProvisioningUnknown {
		return BoolUnknown
	}
	return UnknownFromBool(it == ProvisioningCanceled)
}

func (it ProvisioningState) IsCreating() UnknownBool {
	if it == ProvisioningUnknown {
		return BoolUnknown
	}
	return UnknownFromBool(it == ProvisioningCreating)
}

func (it ProvisioningState) IsDeleting() UnknownBool {
	if it == ProvisioningUnknown {
		return BoolUnknown
	}
	return UnknownFromBool(it == ProvisioningDeleting)
}

func (it ProvisioningState) IsFailed() UnknownBool {
	if it == ProvisioningUnknown {
		return BoolUnknown
	}
	return UnknownFromBool(it == ProvisioningFailed)
}

func (it ProvisioningState) IsSucceeded() UnknownBool {
	if it == ProvisioningUnknown {
		return BoolUnknown
	}
	return UnknownFromBool(it == ProvisioningSucceeded)
}

func (it ProvisioningState) IsUpdating() UnknownBool {
	if it == ProvisioningUnknown {
		return BoolUnknown
	}
	return UnknownFromBool(it == ProvisioningUpdating)
}


