// Code generated by "stringer -type AzureResourceTag"; DO NOT EDIT.

package inzure

import "fmt"

const _AzureResourceTag_name = "ResourceUnsetTResourceUnknownTResourceGroupTStorageAccountTContainerTQueueTFileTTableTProviderTNetworkSecurityGroupTVirtualNetworkTVirtualMachineTSubnetTNetworkInterfaceTIPConfigurationTPublicIPTWebAppTFunctionTDataLakeTDataLakeStoreTDataLakeAnalyticsTSQLServerTWebAppSlotTRedisServerTRecommendationTSQLDatabaseTVirtualMachineScaleSetTApiTApiServiceTApiOperationTApiBackendTApiServiceProductTServiceBusTServiceFabricTApiSchemaTLoadBalancerTFrontendIPConfigurationTApplicationSecurityGroupTKeyVaultTCosmosDBTPostgresServerTPostgresDBT"

var _AzureResourceTag_index = [...]uint16{0, 14, 30, 44, 59, 69, 75, 80, 86, 95, 116, 131, 146, 153, 170, 186, 195, 202, 211, 220, 234, 252, 262, 273, 285, 300, 312, 335, 339, 350, 363, 374, 392, 403, 417, 427, 440, 464, 489, 498, 507, 522, 533}

func (i AzureResourceTag) String() string {
	if i >= AzureResourceTag(len(_AzureResourceTag_index)-1) {
		return fmt.Sprintf("AzureResourceTag(%d)", i)
	}
	return _AzureResourceTag_name[_AzureResourceTag_index[i]:_AzureResourceTag_index[i+1]]
}
