// Code generated by "stringer -type SearchTarget"; DO NOT EDIT.

package inzure

import "fmt"

const _SearchTarget_name = "TargetSearchUnsetTargetStorageAccountsTargetNetworkTargetAppServiceTargetDataLakesTargetSQLTargetRedisTargetRecommendationsTargetAPIsTargetKeyVaultsTargetCosmosDBsTargetLoadBalancersTargetPostgres"

var _SearchTarget_index = [...]uint8{0, 17, 38, 51, 67, 82, 91, 102, 123, 133, 148, 163, 182, 196}

func (i SearchTarget) String() string {
	if i >= SearchTarget(len(_SearchTarget_index)-1) {
		return fmt.Sprintf("SearchTarget(%d)", i)
	}
	return _SearchTarget_name[_SearchTarget_index[i]:_SearchTarget_index[i+1]]
}
